### ISSUE TITLE
Running error (object has no attribute 'stderr')

### ISSUE THREAD

**Issue by madeindjs** [gh640/SublimePhpArrayConverter#1]
When I run `PhpArrayConverter` on **Sublime Text (build 3126)** I got:

> Traceback (most recent call last):
>   File "/opt/sublime_text/sublime_plugin.py", line 818, in run_
>     return self.run(edit)
>   File "PhpArrayConverter in /home/arousseau/.config/sublime-text-3/Installed Packages/PhpArrayConverter.sublime-package", line 44, in run
>   File "PhpArrayConverter in /home/arousseau/.config/sublime-text-3/Installed Packages/PhpArrayConverter.sublime-package", line 72, in convert_array
> AttributeError: 'PhpArrayConverterConvertCommand' object has no attribute 'stderr'

Is it needed to install something to run PhpArrayConverter?

**Comment by gh640** [comment]
Thank you for sharing the issue.

This package needs `php` command to tokenize php sources. If you have already installed `php` and the package doesn't work, try setting `path` in the package setting so that Sublime Text can find `php` command. 

But the AttributeError is caused by my mistake and it should show a proper error message in the status bar. I fixed the code in the following commit and released the new version 0.1.2.

https://github.com/gh640/SublimePhpArrayConverter/commit/d5564baad03bae99623647481894c293b57575ed

I hope this helps.

**Comment by madeindjs** [comment]
Perfect! Thank you very much! :+1:

**Comment by gh640** [comment]
Thank you, too :)
